# -*- coding: utf-8 -*-
"""Week_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FYXvENwTe_uCb_swo01h-vF1V1yql4UN
"""

import pandas as pd

data = [1, 4, 9, 6, 7]
ind = ['a', 'x', 'c', 2, 'e']

series = pd.Series(data, index=ind)
print(series)

import pandas as pd

data = {'Bilal': 42, 'Ayesha': 38, 'Hadia': 39}

series = pd.Series(data)
print(series)

import pandas as pd

data = {
    'day': ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'],
    'temperature': [32, 35, 28, 24, 32, 31],
    'windspeed': [6, 7, 2, 7, 4, 2],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']
}

df = pd.DataFrame(data)
print(df)

import pandas as pd

data = {
    'day': ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'],
    'temperature': [32, 35, 28, 24, 32, 31],
    'windspeed': [6, 7, 2, 7, 4, 2],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']
}

index = ['a', 'b', 'c', 'd', 'e', 'f']

df = pd.DataFrame(data, index=index)
print(df)

import pandas as pd

data = {
    'day': ['1/1/2017', '1/2/2017', '1/3/2017', '1/4/2017', '1/5/2017', '1/6/2017'],
    'temperature': [32, 35, 28, 24, 32, 31],
    'windspeed': [6, 7, 2, 7, 4, 2],
    'event': ['Rain', 'Sunny', 'Snow', 'Snow', 'Rain', 'Sunny']
}

index = ['a', 'b', 'c', 'd', 'e', 'f']

df = pd.DataFrame(data, index=index)
print(df)

mean_temp = df['temperature'].mean()
max_temp = df['temperature'].max()
min_temp = df['temperature'].min()

print("Mean temperature:", mean_temp)
print("Max temperature:", max_temp)
print("Min temperature:", min_temp)

import pandas as pd

df = pd.read_csv('people.csv',
                 usecols=["First Name", "Sex", "Email", "Phone", "Job Title"],
                 index_col=["Sex", "Job Title"],
                 skiprows=[1, 5])

df.to_csv('NewPeople.csv')

import pandas as pd

# Read the Excel file, specifying sheet to read and columns to use
df = pd.read_excel('SampleWork.xlsx',
                   sheet_name=0,
                   usecols=[0, -1],
                   header=1,
                   skiprows=[2])

# Export the DataFrame to a new Excel sheet
df.to_excel('NewSheet.xlsx', index=False)

import pandas as pd

data = {
    'Name': ['Ali', 'Hifza', 'Bilal', 'Ahmed', 'Sara'],
    'Qualification': ['BSc', 'MS', 'PhD', 'BS', 'MS']
}

AICP_DF = pd.DataFrame(data)
print("AICP_DF:")
print(AICP_DF)

df1 = AICP_DF[['Name', 'Qualification']]
print("df1:")
print(df1)

AICP_DF['Height'] = [5.1, 6.2, 5.1, 5.2, 5.1]
print("AICP_DF with Height column:")
print(AICP_DF)

AICP_DF.set_index('Name', inplace=True)
print("AICP_DF with Name as index:")
print(AICP_DF)

row_hifza = AICP_DF.loc['Hifza']
print("Row with index 'Hifza':")
print(row_hifza)

row_3 = AICP_DF.iloc[2]  # index 2 corresponds to the row with index 'Bilal'
print("Row with index 3 (Bilal):")
print(row_3)

AICP_DF.drop(index='Bilal', inplace=True)
print("AICP_DF after dropping 'Bilal':")
print(AICP_DF)

